version: '2.1'
services:

  fantasy-football-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=fantasy_football
    healthcheck:
      test: "/usr/bin/mysql --user=testuser --password=testpass --execute \"use fantasy_football;\""
      interval: 2s
      timeout: 20s
      retries: 10

  fantasy-football-app:
    image: fantasy-football-app
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://fantasy-football-db:3306/fantasy_football?useSSL=false
      - SPRING_DATASOURCE_USERNAME=testuser
      - SPRING_DATASOURCE_PASSWORD=testpass
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      fantasy-football-db:
        condition: service_healthy